# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpcCalc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'grpcCalc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egrpcCalc.proto\x12\x08grpccalc\" \n\x08Operands\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"&\n\x06Result\x12\r\n\x05value\x18\x01 \x01(\x01\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xc0\x01\n\nCalculator\x12+\n\x03\x41\x64\x64\x12\x12.grpccalc.Operands\x1a\x10.grpccalc.Result\x12+\n\x03Sub\x12\x12.grpccalc.Operands\x1a\x10.grpccalc.Result\x12+\n\x03Mul\x12\x12.grpccalc.Operands\x1a\x10.grpccalc.Result\x12+\n\x03\x44iv\x12\x12.grpccalc.Operands\x1a\x10.grpccalc.Resultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpcCalc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPERANDS']._serialized_start=28
  _globals['_OPERANDS']._serialized_end=60
  _globals['_RESULT']._serialized_start=62
  _globals['_RESULT']._serialized_end=100
  _globals['_CALCULATOR']._serialized_start=103
  _globals['_CALCULATOR']._serialized_end=295
# @@protoc_insertion_point(module_scope)
