# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: miner.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'miner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bminer.proto\x12\x05miner\"\x07\n\x05\x45mpty\"\x17\n\x06IntMsg\x12\r\n\x05value\x18\x01 \x01(\x05\"\'\n\rTransactionID\x12\x16\n\x0etransaction_id\x18\x01 \x01(\x05\"*\n\x10\x43hallengeRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\x05\"&\n\x11\x43hallengeResponse\x12\x11\n\tchallenge\x18\x01 \x01(\x05\" \n\x0eStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\" \n\x0eWinnerResponse\x12\x0e\n\x06winner\x18\x01 \x01(\x05\"E\n\x0eSolutionStruct\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x10\n\x08solution\x18\x02 \x01(\t\x12\x11\n\tchallenge\x18\x03 \x01(\x05\"H\n\tSubmitReq\x12\x16\n\x0etransaction_id\x18\x01 \x01(\x05\x12\x11\n\tclient_id\x18\x02 \x01(\x05\x12\x10\n\x08solution\x18\x03 \x01(\t\"\x1b\n\tSubmitRes\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\xf6\x02\n\x05Miner\x12/\n\x10getTransactionID\x12\x0c.miner.Empty\x1a\r.miner.IntMsg\x12\x41\n\x0cgetChallenge\x12\x17.miner.ChallengeRequest\x1a\x18.miner.ChallengeResponse\x12\x46\n\x14getTransactionStatus\x12\x17.miner.ChallengeRequest\x1a\x15.miner.StatusResponse\x12\x35\n\x0fsubmitChallenge\x12\x10.miner.SubmitReq\x1a\x10.miner.SubmitRes\x12;\n\tgetWinner\x12\x17.miner.ChallengeRequest\x1a\x15.miner.WinnerResponse\x12=\n\x0bgetSolution\x12\x17.miner.ChallengeRequest\x1a\x15.miner.SolutionStructb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'miner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=22
  _globals['_EMPTY']._serialized_end=29
  _globals['_INTMSG']._serialized_start=31
  _globals['_INTMSG']._serialized_end=54
  _globals['_TRANSACTIONID']._serialized_start=56
  _globals['_TRANSACTIONID']._serialized_end=95
  _globals['_CHALLENGEREQUEST']._serialized_start=97
  _globals['_CHALLENGEREQUEST']._serialized_end=139
  _globals['_CHALLENGERESPONSE']._serialized_start=141
  _globals['_CHALLENGERESPONSE']._serialized_end=179
  _globals['_STATUSRESPONSE']._serialized_start=181
  _globals['_STATUSRESPONSE']._serialized_end=213
  _globals['_WINNERRESPONSE']._serialized_start=215
  _globals['_WINNERRESPONSE']._serialized_end=247
  _globals['_SOLUTIONSTRUCT']._serialized_start=249
  _globals['_SOLUTIONSTRUCT']._serialized_end=318
  _globals['_SUBMITREQ']._serialized_start=320
  _globals['_SUBMITREQ']._serialized_end=392
  _globals['_SUBMITRES']._serialized_start=394
  _globals['_SUBMITRES']._serialized_end=421
  _globals['_MINER']._serialized_start=424
  _globals['_MINER']._serialized_end=798
# @@protoc_insertion_point(module_scope)
